=== ambreea/my_projects/JavaWebServicesXML/JAXP/JAXP_XPath/books.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="book" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="book">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="author" type="xs:string" />
                <xs:element name="book_name" type="xs:string" />
                <xs:element name="type" type="xs:string" />
                <xs:element name="price" type="xs:decimal" />
                <xs:element name="publish_date" type="xs:date" />
                <xs:element name="description" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ambreea/my_projects/JavaWebServicesXML/JAXP/JAXP_DOM/books.xml
<?xml version="1.0" encoding="UTF-8"?>

<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="books.xsd">
    <book>
        <author>Gambardella, Matthew</author>
        <book_name>XML Developer's Guide</book_name>
        <type>Computer</type>
        <price>44.95</price>
        <publish_date>2000-10-01</publish_date>
        <description>An in-depth look at creating applications with XML.</description>
    </book>
    <book>
        <author>Ralls, Kim</author>
        <book_name>Midnight Rain</book_name>
        <type>Fantasy</type>
        <price>5.95</price>
        <publish_date>2002-12-16</publish_date>
        <description>A former architect battles corporate zombies,an evil sorceress, and her own childhood to become queen of the world.</description>
    </book>
    <book>
        <author>Corets, Eva</author>
        <book_name>Maeve Ascendant</book_name>
        <type>Fantasy</type>
        <price>5.95</price>
        <publish_date>2000-11-17</publish_date>
        <description>After the collapse of a nanotechnology society in England, the young survivors lay the foundation for a new society.</description>
    </book>
    <book>
        <author>Corets, Eva</author>
        <book_name>Oberon's Legacy</book_name>
        <type>Fantasy</type>
        <price>5.95</price>
        <publish_date>2001-03-10</publish_date>
        <description>In post-apocalypse England, the mysterious agent known only as Oberon helps to create a new life for the inhabitants of London. Sequel to Maeve Ascendant.</description>
    </book>
    <book>
        <author>Corets, Eva</author>
        <book_name>The Sundered Grail</book_name>
        <type>Fantasy</type>
        <price>5.95</price>
        <publish_date>2001-09-10</publish_date>
        <description>The two daughters of Maeve, half-sisters, battle one another for control of England. Sequel to Oberon's Legacy.</description>
    </book>
    <book>
        <author>Randall, Cynthia</author>
        <book_name>Lover Birds</book_name>
        <type>Romance</type>
        <price>4.95</price>
        <publish_date>2003-09-02</publish_date>
        <description>When Carla meets Paul at an ornithology conference, tempers fly as feathers get ruffled.</description>
    </book>
    <book>
        <author>Thurman, Paula</author>
        <book_name>Splish Splash</book_name>
        <type>Romance</type>
        <price>4.95</price>
        <publish_date>2004-11-02</publish_date>
        <description>A deep sea diver finds true love twenty thousand leagues beneath the sea.</description>
    </book>
    <book>
        <author>Knorr, Stefan</author>
        <book_name>Creepy Crawlies</book_name>
        <type>Horror</type>
        <price>4.95</price>
        <publish_date>2005-12-06</publish_date>
        <description> An anthology of horror stories about roaches, centipedes, scorpions  and other insects.</description>
    </book>
    <book>
        <author>Kress, Peter</author>
        <book_name>Paradox Lost</book_name>
        <type>Science Fiction</type>
        <price>6.95</price>
        <publish_date>2006-11-02</publish_date>
        <description>After an inadvertant trip through a Heisenberg Uncertainty Device, James Salway discovers the problems of being quantum.</description>
    </book>
    <book>
        <author>O'Brien, Tim</author>
        <book_name>Microsoft .NET: The Programming Bible</book_name>
        <type>Computer</type>
        <price>36.95</price>
        <publish_date>2006-12-09</publish_date>
        <description>Microsoft's .NET initiative is explored in detail in this deep programmer's reference.</description>
    </book>
    <book>
        <author>O'Brien, Tim</author>
        <book_name>MSXML3: A Comprehensive Guide</book_name>
        <type>Computer</type>
        <price>36.95</price>
        <publish_date>2007-12-01</publish_date>
        <description>The Microsoft MSXML3 parser is covered in detail, with attention to XML DOM interfaces, XSLT processing, SAX and more.</description>
    </book>
    <book>
        <author>Galos, Mike</author>
        <book_name>Visual Studio 7: A Comprehensive Guide</book_name>
        <type>Computer</type>
        <price>49.95</price>
        <publish_date>2008-04-16</publish_date>
        <description>Microsoft Visual Studio 7 is explored in depth, looking at how Visual Basic, Visual C++, C#, and ASP+ are integrated into a comprehensive development environment.</description>
    </book>
</books>
